import type { Metadata } from 'next'
import Link from 'next/link'
import { createCatalogueClient } from '@/lib/supabase/server'

export const dynamic = 'force-dynamic'
export const revalidate = 0
export const metadata: Metadata = {title:'Careers | Folus Emporium',description:'Explore career opportunities and learn what it means to work with Folus Emporium.'}
function paras(text?:string|null){return String(text||'').replace(/\\n/g,'\n').split(/\n\s*\n/).map(p=>p.trim()).filter(Boolean).map((p,i)=><p key={i}>{p}</p>)}
const fallback={eyebrow:'Careers',title:'Grow with a business that is still being built.',intro:'Folus Emporium is developing its food, ecommerce, operations and customer-service capabilities. We value practical thinkers who are willing to learn, take ownership and help improve the way work gets done.',content:'We value ownership, customer focus, continuous improvement, professionalism and respect. Openings are advertised when positions become available.',secondary_title:'Current openings',secondary_content:'No publicly advertised vacancy at the moment. If you would like to be considered for future opportunities, send a concise CV and a short introduction explaining the area in which you can contribute.'}
export default async function CareersPage(){const s=await createCatalogueClient();const {data:career}=await s.from('company_pages').select('*').eq('page_key','careers').eq('is_published',true).maybeSingle();const c=career||fallback;return <main><header className="nav"><div className="container nav-inner"><Link className="brand" href="/"><img src="/folus-emporium-circular-logo.png" alt="Folus Emporium logo"/><span>FOLUS<br/>EMPORIUM<small>Curating Excellence for Life’s Finest Moments.</small></span></Link><nav className="navlinks"><Link href="/">Home</Link><Link href="/shop">Shop</Link><Link href="/about">About Us</Link><Link href="/blog">Blog</Link></nav></div></header><section className="content-hero"><div className="container content-hero-grid"><div><div className="eyebrow">{c.eyebrow||'Careers'}</div><h1>{c.title}</h1>{paras(c.intro)}<div className="hero-actions"><a className="btn btn-primary" href="mailto:info@folusemporium.com?subject=Career%20Interest%20-%20Folus%20Emporium">Send your CV</a><Link className="btn btn-outline" href="/about">Learn about us</Link></div></div><div className="content-brand-card"><span className="eyebrow">Working at Folus Emporium</span><strong>Small team. Real responsibility. Visible impact.</strong><p>Contribute ideas, strengthen systems and improve customer outcomes as the business grows.</p></div></div></section><section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Our culture</div><h2>What we value in people</h2></div></div><div className="story-panel">{paras(c.content)}</div></div></section><section className="section soft-section"><div className="container"><div className="section-head"><div><div className="eyebrow">Current openings</div><h2>{c.secondary_title||'Current openings'}</h2></div></div><div className="story-panel">{paras(c.secondary_content)}<a className="btn btn-primary" href="mailto:info@folusemporium.com?subject=Career%20Interest%20-%20Folus%20Emporium">Email your application</a></div></div></section><section className="cta"><div className="container"><div className="cta-box"><div><div className="eyebrow">Know our business first</div><h2>Read the story behind Folus Emporium.</h2></div><Link className="btn btn-primary" href="/about#story">Our Story</Link></div></div></section></main>}
