import Link from 'next/link'
import type { Metadata } from 'next'
import { createCatalogueClient } from '@/lib/supabase/server'
import { StorefrontHeader } from '@/components/storefront-ui'

export const metadata:Metadata={title:'Help Desk',description:'Help and guidance for shopping, accounts, payments, delivery, order tracking, wishlist, coupons and support on Folus Emporium.'}

const fallback={announcement:'Serving homes & businesses across Nigeria.',utilityLinks:[['Track Order','/account'],['FAQ','/faq'],['Contact Us','/contact']] as [string,string][],social:{facebook:'https://www.facebook.com/folusemporiumltd',instagram:'',tiktok:'https://www.tiktok.com/@folusemporium25',youtube:'',linkedin:'',whatsapp:'https://wa.me/2349168157255'},navigation:[['Home','/'],['Shop','/shop'],['Categories','/shop'],['About Us','/about'],['Our Story','/about#story'],['Blog','/blog'],['Careers','/careers'],['Contact Us','/contact']] as [string,string][]}

const topics=[['account','Account & Registration','Create an account, sign in, update your profile and change your password.'],['orders','Shopping & Placing Orders','Browse products, choose package sizes, add to cart and proceed to checkout.'],['payments','Payments','Understand Paystack online payment and Pay After Delivery where available.'],['tracking','Order Tracking','Follow your order from pending to processing, shipped and delivered.'],['delivery','Delivery & Fulfilment','Understand delivery information, delivery zones and fulfilment.'],['wishlist','Wishlist','Save products you are interested in and return to them later.'],['coupons','Coupons & Discounts','Apply valid discount codes during checkout.'],['returns','Returns & Refunds','Find the right policy and support route for return or refund enquiries.'],['newsletter','Newsletter & Communication','Manage product updates, offers and newsletter subscription.'],['support','Contact Support','Reach Folus Emporium when you need personal assistance.']]

export default async function HelpPage(){
 const supabase=await createCatalogueClient(); const [{data:storefrontContent},{data:categories}]=await Promise.all([supabase.from('storefront_content').select('config').eq('id',true).maybeSingle(),supabase.from('categories').select('name,slug').order('name')]); const config={...fallback,...((storefrontContent?.config??{}) as Partial<typeof fallback>)}
 return <main className="help-shell"><StorefrontHeader config={config} categories={categories??[]}/>
 <section className="help-hero"><div className="container"><div className="eyebrow">Folus Emporium Help Desk</div><h1>How can we help you?</h1><p>Find clear guidance on using the Folus Emporium website—from finding products and creating an account to checkout, payment, delivery, tracking, wishlist, discounts and support.</p><div className="help-search"><input aria-label="Search help topics" placeholder="Search help topics using your browser (Ctrl + F / Find in page)" readOnly/><Link className="btn btn-primary" href="#topics">Browse help topics</Link></div></div></section>
 <section className="container" id="topics"><div className="help-grid">{topics.map(([id,title,text])=><Link className="help-topic" href={`#${id}`} key={id}><strong>{title}</strong><span>{text}</span></Link>)}</div></section>
 <div className="container help-layout"><aside className="help-sidebar"><h3>Help Categories</h3>{topics.map(([id,title])=><Link href={`#${id}`} key={id}>{title}</Link>)}</aside><div className="help-main">
 <section className="help-card" id="account"><h2>Account & Registration</h2><p>You can browse the Folus Emporium shop without signing in. An account is required when you proceed from your cart to checkout so your order, contact details and order history can be linked securely to you.</p><ol><li>Select <strong>Account</strong> in the header.</li><li>Choose sign in if you already have an account, or create a new account.</li><li>Complete your customer details and confirm your email when requested.</li><li>After signing in, use <strong>My Account</strong> to view your profile, orders, newsletter preference and password settings.</li></ol><div className="quick-links"><Link href="/login">Sign in</Link><Link href="/login?mode=signup">Create account</Link><Link href="/account">My Account</Link></div></section>
 <section className="help-card" id="orders"><h2>Shopping & Placing an Order</h2><ol><li>Open <Link href="/shop">Shop</Link> from the main navigation.</li><li>Search by product name or filter by category.</li><li>Open a product to review its description, price, package size and availability.</li><li>Select the required package size and quantity, then add it to your cart.</li><li>Open the cart and review quantities before proceeding.</li><li>At checkout, sign in or register if you have not already done so.</li><li>Enter or confirm your delivery details, apply a coupon if available, choose a payment method and submit the order.</li></ol><p>You can continue shopping before checkout, and items already placed in your cart remain available while you browse.</p><div className="quick-links"><Link href="/shop">Start shopping</Link><Link href="/cart">View cart</Link></div></section>
 <section className="help-card" id="payments"><h2>Payments</h2><p>Folus Emporium supports secure online checkout through Paystack and may also offer Pay After Delivery for eligible orders. Your order page shows the payment method and payment status attached to each order.</p><ul><li><strong>Paystack:</strong> complete payment on the secure Paystack payment page. A successful payment updates the order as paid.</li><li><strong>Pay After Delivery:</strong> when available, your order is confirmed for fulfilment and payment is handled according to the selected delivery arrangement.</li><li>If an online payment is interrupted, do not repeatedly create duplicate orders. Check My Account first to confirm the order/payment status.</li></ul><div className="quick-links"><Link href="/account">Check payment status</Link><Link href="/contact">Report a payment issue</Link></div></section>
 <section className="help-card" id="tracking"><h2>Order Tracking</h2><p>Your account keeps your order history and current fulfilment status in one place.</p><ol><li>Sign in and open <Link href="/account">My Account</Link>.</li><li>Find the relevant order in Order History.</li><li>Review the order status, payment status, items, total, delivery address and dates.</li><li>The normal fulfilment journey is <strong>Pending → Processing → Shipped → Delivered</strong>. Cancelled orders are shown separately.</li></ol><p>Where available, invoices or receipts can also be accessed from your order information.</p></section>
 <section className="help-card" id="delivery"><h2>Delivery & Fulfilment</h2><p>Delivery charges and availability depend on the delivery information selected during checkout. Ensure your phone number and delivery address are accurate before submitting an order.</p><ul><li>Orders move into processing after confirmation/payment according to the selected payment method.</li><li>When the order is dispatched, its status can be updated to Shipped.</li><li>After successful fulfilment, it is marked Delivered.</li><li>For delivery questions, provide your order reference when contacting support.</li></ul><div className="quick-links"><Link href="/shipping-policy">Shipping policy</Link><Link href="/account">Track order</Link></div></section>
 <section className="help-card" id="wishlist"><h2>Wishlist</h2><p>The Wishlist helps you save products for later without adding them immediately to your cart.</p><ol><li>Select the heart icon on a product.</li><li>Open <Link href="/wishlist">Wishlist</Link> from the header.</li><li>Review saved products and return to the product page when you are ready to buy.</li><li>You can remove products from your wishlist at any time.</li></ol></section>
 <section className="help-card" id="coupons"><h2>Coupons & Discounts</h2><p>If you have a valid Folus Emporium coupon code, enter it during checkout before payment. Validity can depend on activation status, expiry, usage limits or other campaign conditions. The discount amount will be reflected in your order total when the code is accepted.</p></section>
 <section className="help-card" id="returns"><h2>Returns & Refunds</h2><p>For return or refund enquiries, first review the relevant policy and then contact Folus Emporium with your order reference, product information and a clear explanation of the issue. Payment status in My Account may show refunded when a refund has been processed.</p><div className="quick-links"><Link href="/return-policy">Return policy</Link><Link href="/contact">Contact support</Link></div></section>
 <section className="help-card" id="newsletter"><h2>Newsletter & Communication</h2><p>You can subscribe to Folus Emporium product updates, offers and useful food information from the website footer or during registration. Registered customers can review or change their newsletter preference from My Account. You may unsubscribe when you no longer wish to receive marketing messages.</p><div className="quick-links"><Link href="/account">Newsletter preference</Link><Link href="/newsletter">Newsletter</Link></div></section>
 <section className="help-card" id="support"><h2>Contact Support</h2><p>If the Help Desk does not resolve your issue, contact Folus Emporium directly. For order-related enquiries, include your order reference so the team can assist faster.</p><div className="help-contact"><a className="btn btn-primary" href="https://wa.me/2349168157255">WhatsApp Support</a><a className="btn btn-outline" href="mailto:folusemporium@gmail.com">Email Support</a><Link className="btn btn-outline" href="/contact">Contact page</Link></div></section>
 </div></div>
 <footer className="footer luxury-footer"><div className="container footer-links-grid"><div><h3>Company</h3><Link href="/about">About Us</Link><Link href="/about#story">Our Story</Link><Link href="/contact">Contact Us</Link></div><div><h3>Shop</h3><Link href="/shop">All Products</Link><Link href="/wishlist">Wishlist</Link></div><div><h3>Customer Service</h3><Link href="/faq">FAQs</Link><Link href="/shipping-policy">Shipping Policy</Link><Link href="/return-policy">Return Policy</Link></div><div><h3>My Account</h3><Link href="/login">Login</Link><Link href="/login?mode=signup">Register</Link><Link href="/wishlist">Wishlist</Link><Link href="/account">Order Tracking</Link><Link href="/help">Help Desk</Link></div><div className="footer-contact"><h3>Need help?</h3><a href="mailto:folusemporium@gmail.com">folusemporium@gmail.com</a><a href="tel:+2349168157255">+234 916 815 7255</a><a href="https://wa.me/2349168157255">WhatsApp Support</a></div></div></footer>
 </main>
}
