import type { Metadata } from 'next'
import Link from 'next/link'
import { createCatalogueClient } from '@/lib/supabase/server'

export const dynamic = 'force-dynamic'
export const revalidate = 0
export const metadata: Metadata = {title:'Blog | Folus Emporium',description:'Food tips, product education, processing insights and practical kitchen ideas from Folus Emporium.'}
function paras(text?:string|null){return String(text||'').replace(/\\n/g,'\n').split(/\n\s*\n/).map(p=>p.trim()).filter(Boolean).map((p,i)=><p key={i}>{p}</p>)}
export default async function BlogPage(){const s=await createCatalogueClient();const {data:posts}=await s.from('blog_posts').select('*').eq('is_published',true).order('published_at',{ascending:false,nullsFirst:false});return <main><header className="nav"><div className="container nav-inner"><Link className="brand" href="/"><img src="/folus-emporium-circular-logo.png" alt="Folus Emporium logo"/><span>FOLUS<br/>EMPORIUM<small>Curating Excellence for Life’s Finest Moments.</small></span></Link><nav className="navlinks"><Link href="/">Home</Link><Link href="/shop">Shop</Link><Link href="/about">About Us</Link><Link href="/contact">Contact Us</Link></nav></div></header><section className="content-hero"><div className="container"><div className="eyebrow">Folus Emporium Journal</div><h1>Useful food knowledge for everyday living.</h1><p style={{maxWidth:760}}>Practical ideas about food products, storage, processing, preparation and everyday choices for homes and businesses.</p></div></section><section className="section"><div className="container"><div className="blog-grid">{posts?.map((post:any)=><article className="blog-card" key={post.id}>{post.featured_image_url?<a href={`#${post.slug}`} style={{display:'block',margin:'-18px -18px 16px',overflow:'hidden',borderRadius:'14px 14px 0 0'}}><img src={post.featured_image_url} alt={post.title} style={{width:'100%',aspectRatio:'3/2',objectFit:'cover',display:'block'}}/></a>:null}<span>{post.category||'Article'}</span><h2>{post.title}</h2><p>{post.excerpt}</p><div className="blog-meta">{post.published_at?new Date(post.published_at).toLocaleDateString('en-NG',{year:'numeric',month:'long',day:'numeric'}):''}</div><a href={`#${post.slug}`}>Read article →</a></article>)}</div>{!posts?.length?<div className="story-panel"><p>No published articles yet.</p></div>:null}</div></section>{posts?.map((post:any,i:number)=><section className={`section ${i%2===0?'soft-section':''}`} id={post.slug} key={post.id}><div className="container article-wrap">{post.featured_image_url?<img src={post.featured_image_url} alt={post.title} style={{width:'100%',maxHeight:520,objectFit:'cover',borderRadius:18,marginBottom:24}}/>:null}<div className="eyebrow">{post.category||'Article'}</div><h2>{post.title}</h2>{paras(post.content)}</div></section>)}<section className="cta"><div className="container"><div className="cta-box"><div><div className="eyebrow">From the blog to the kitchen</div><h2>Explore the Folus Emporium product collection.</h2></div><Link className="btn btn-primary" href="/shop">Shop now</Link></div></div></section></main>}
