import type { Metadata } from 'next'
import Link from 'next/link'
import { createCatalogueClient } from '@/lib/supabase/server'

export const dynamic='force-dynamic'
export const revalidate=0
export const metadata: Metadata={title:'Blog | Folus Emporium',description:'Food tips, product education, processing insights and practical kitchen ideas from Folus Emporium.'}

const fallback=[
 {id:'processing',category:'Food Education',title:'Why proper food processing matters',slug:'why-proper-food-processing-matters',excerpt:'Good processing is about more than appearance. It supports consistency, cleanliness, shelf stability and a better customer experience.',content:'Food processing affects more than convenience. Careful handling, cleaning, drying, milling and packaging can influence product consistency, hygiene, storage behaviour and the final experience customers have in the kitchen.\n\nAt Folus Emporium, our goal is to keep improving these steps so products are practical to use, clearly presented and handled with care from sourcing through packaging.',published_at:'2026-09-01'},
 {id:'plantain',category:'Product Guide',title:'Plantain Flour: simple ways to use it',slug:'plantain-flour-simple-ways-to-use-it',excerpt:'From swallow and porridge to pancakes and baking, plantain flour can be a versatile addition to the pantry.',content:'Plantain Flour can work well beyond the traditional swallow. Depending on your recipe, it may also be used in porridge-style meals, pancakes and selected baking applications.\n\nFor best results, start with the preparation method suited to the particular dish and adjust liquid gradually to achieve the texture you want.',published_at:'2026-09-01'},
 {id:'poundo',category:'Product Guide',title:'Poundo Yam Flour is not Amala Flour',slug:'poundo-yam-flour-is-not-amala-flour',excerpt:'Understand the difference, what Poundo Yam Flour is designed for, and how to get a smooth, satisfying result.',content:'Poundo Yam Flour is intended to produce a smooth pounded-yam style swallow. Amala flour is prepared differently and has a distinct colour, flavour and texture. The two products should not be treated as interchangeable.\n\nWhen preparing Poundo Yam Flour, add the flour gradually to hot water while stirring continuously until the mixture becomes smooth, cohesive and reaches your preferred firmness.',published_at:'2026-09-01'},
 {id:'storage',category:'Kitchen Tips',title:'How to store flours and powders properly',slug:'how-to-store-flours-and-powders-properly',excerpt:'Airtight containers, dry storage and clean scoops can help protect texture, flavour and product quality after opening.',content:"Keep dry food products tightly sealed in a cool, dry place away from direct sunlight, steam and moisture. Always use a clean, dry scoop and close the package or storage container immediately after use.\n\nGood storage habits help reduce exposure to humidity and contaminants and make it easier to preserve the product's intended quality after opening.",published_at:'2026-09-01'},
]
function paras(text?:string|null){return String(text||'').replace(/\\n/g,'\n').split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean).map((x,i)=><p key={i}>{x}</p>)}

export default async function BlogPage(){
 const s=await createCatalogueClient(); const {data,error}=await s.rpc('list_published_blog_posts'); const posts=!error&&data?.length?data:fallback;
 return <main>
  <header className="nav"><div className="container nav-inner"><Link className="brand" href="/"><img src="/folus-emporium-circular-logo.png" alt="Folus Emporium logo"/><span>FOLUS<br/>EMPORIUM<small>Curating Excellence for Life’s Finest Moments.</small></span></Link><nav className="navlinks"><Link href="/">Home</Link><Link href="/shop">Shop</Link><Link href="/about">About Us</Link><Link href="/contact">Contact Us</Link></nav></div></header>
  <section className="content-hero"><div className="container"><div className="eyebrow">Folus Emporium Journal</div><h1>Useful food knowledge for everyday living.</h1><p style={{maxWidth:760}}>Our blog shares practical ideas about food products, storage, processing, preparation and the everyday choices that help homes and businesses get more value from what they buy.</p></div></section>
  <section className="section"><div className="container"><div className="blog-grid">{posts.map((post:any)=><article className="blog-card" key={post.id}><span>{post.category||'Article'}</span><h2>{post.title}</h2>{post.featured_image_url?<a href={`#${post.slug}`} style={{display:'block',margin:'14px 0 16px',overflow:'hidden',borderRadius:14}}><img src={post.featured_image_url} alt={post.title} style={{width:'100%',aspectRatio:'3/2',objectFit:'cover',display:'block'}}/></a>:null}<p>{post.excerpt}</p><div className="blog-meta">{post.published_at?new Date(post.published_at).toLocaleDateString('en-NG',{year:'numeric',month:'long',day:'numeric'}):'September 2026'}</div><a href={`#${post.slug}`}>Read article →</a></article>)}</div></div></section>
  {posts.map((post:any,i:number)=><section className={`section ${i%2===0?'soft-section':''}`} id={post.slug} key={post.id}><div className="container article-wrap"><div className="eyebrow">{post.category||'Article'}</div><h2>{post.title}</h2>{post.featured_image_url?<img src={post.featured_image_url} alt={post.title} style={{width:'100%',maxHeight:520,objectFit:'cover',borderRadius:18,margin:'10px 0 24px'}}/>:null}{paras(post.content)}</div></section>)}
  <section className="cta"><div className="container"><div className="cta-box"><div><div className="eyebrow">From the blog to the kitchen</div><h2>Explore the Folus Emporium product collection.</h2></div><Link className="btn btn-primary" href="/shop">Shop now</Link></div></div></section>
 </main>
}
