import type { Metadata } from 'next'
import Link from 'next/link'
import { createCatalogueClient } from '@/lib/supabase/server'

export const dynamic='force-dynamic'
export const revalidate=0
export const metadata: Metadata={title:'About Us | Folus Emporium',description:'Learn about Folus Emporium, our purpose, values, story and commitment to quality food products and thoughtful everyday living.'}

const values=[
 ['Quality','We pay attention to sourcing, processing, packaging and presentation so every product reflects the standard we want customers to trust.'],
 ['Integrity','We aim to communicate clearly, price fairly and build long-term relationships with customers, suppliers and partners.'],
 ['Convenience','We create practical food products that help households and businesses save time without compromising everyday usefulness.'],
 ['Growth','We continue learning, improving our processes and expanding our range in response to real customer needs.'],
]
const fallbackAbout={eyebrow:'About Folus Emporium',title:'Thoughtfully curated food products for everyday living.',intro:'Folus Emporium Ltd is a growing Nigerian food and lifestyle business focused on making quality food products more convenient, dependable and accessible to households and businesses.',content:'We work across sourcing, processing, packaging and distribution to serve customers who want dependable food products without unnecessary complexity. Our collection includes flours, powders, pantry staples, mixes, tea and carefully selected food products designed for homes and businesses.',secondary_title:'Our mission and vision',secondary_content:'Mission: To source, process, package and distribute quality food products that support convenient everyday cooking and better customer experiences.\n\nVision: To grow into a recognised food business known for quality, reliable processing, practical innovation and strong relationships across the value chain.'}
const fallbackStory={eyebrow:'Our Story',title:'A growing business shaped by real customer needs.',intro:'Folus Emporium began with a simple idea: make useful, well-presented food and household products easier for people to access.',content:'As customer needs became clearer, the business developed a stronger focus on food sourcing, processing, packaging and distribution. Today, Folus Emporium is building a catalogue of practical products and investing in better systems, stronger supplier relationships, improved packaging and digital commerce.',secondary_title:'Where we are going',secondary_content:'The long-term goal is not simply to sell products. It is to build a trusted brand customers can rely on for quality, convenience and thoughtful service.'}
function clean(text?:string|null){return String(text||'').replace(/\\n/g,'\n')}
function paras(text?:string|null){return clean(text).split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean).map((x,i)=><p key={i}>{x}</p>)}

export default async function AboutPage(){
 const s=await createCatalogueClient(); const {data}=await s.rpc('list_published_company_pages');
 const about=(data||[]).find((r:any)=>r.page_key==='about')||fallbackAbout; const story=(data||[]).find((r:any)=>r.page_key==='story')||fallbackStory;
 return <main>
  <header className="nav"><div className="container nav-inner"><Link className="brand" href="/"><img src="/folus-emporium-circular-logo.png" alt="Folus Emporium logo"/><span>FOLUS<br/>EMPORIUM<small>Curating Excellence for Life’s Finest Moments.</small></span></Link><nav className="navlinks"><Link href="/">Home</Link><Link href="/shop">Shop</Link><Link href="/blog">Blog</Link><Link href="/contact">Contact Us</Link></nav></div></header>
  <section className="content-hero"><div className="container content-hero-grid"><div><div className="eyebrow">{about.eyebrow||'About Folus Emporium'}</div><h1>{about.title}</h1>{paras(about.intro)}<div className="hero-actions"><Link className="btn btn-primary" href="/shop">Shop our products</Link><Link className="btn btn-outline" href="#story">Read our story</Link></div></div><div className="content-brand-card"><img src="/folus-emporium-circular-logo.png" alt="Folus Emporium circular logo"/><strong>Curating Excellence for Life’s Finest Moments.</strong><p>Better ingredients. Better processing. Better experience.</p></div></div></section>
  <section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Who we are</div><h2>Built around quality, trust and convenience.</h2></div></div><div className="content-two-col"><div>{paras(about.content)}<p>Our customers include households as well as supermarkets, restaurants, food vendors, schools, hotels and corporate organisations. As the business grows, our focus remains consistent: provide practical products, improve processing standards and create a customer experience that people can return to with confidence.</p></div><div className="content-stat-card"><span>Our focus</span><strong>Food quality + practical convenience</strong><p>From product selection to packaging and delivery, every part of the experience is designed to make everyday food choices easier.</p></div></div></div></section>
  <section className="section soft-section"><div className="container"><div className="section-head"><div><div className="eyebrow">Purpose</div><h2>{about.secondary_title||'Our mission and vision'}</h2></div></div><div className="content-cards"><article><span>Mission</span><h3>Make dependable food products easier to access.</h3><p>{clean(about.secondary_content).split(/\n\s*\n/)[0]?.replace(/^Mission:\s*/,'')||'To source, process, package and distribute quality food products that support convenient everyday cooking and better customer experiences.'}</p></article><article><span>Vision</span><h3>Build a trusted Nigerian food brand with lasting impact.</h3><p>{clean(about.secondary_content).split(/\n\s*\n/)[1]?.replace(/^Vision:\s*/,'')||'To grow into a recognised food business known for quality, reliable processing, practical innovation and strong relationships across the value chain.'}</p></article><article><span>Promise</span><h3>Better ingredients. Better processing. Better experience.</h3><p>We keep improving how our products are selected, prepared, packaged and delivered so customers can buy with greater confidence.</p></article></div></div></section>
  <section className="section" id="story"><div className="container"><div className="section-head"><div><div className="eyebrow">{story.eyebrow||'Our Story'}</div><h2>{story.title}</h2></div></div><div className="story-panel">{paras(story.intro)}{paras(story.content)}<p>Our journey is still in its early growth stage, and that is exactly why improvement matters so much to us. We are investing in better systems, stronger supplier relationships, improved packaging, digital commerce and a more dependable buying experience for both individual and business customers.</p>{story.secondary_title?<h3>{story.secondary_title}</h3>:null}{paras(story.secondary_content)}</div></div></section>
  <section className="section promise"><div className="container"><div className="section-head"><div><div className="eyebrow">What guides us</div><h2 style={{color:'#fff'}}>Our values</h2></div></div><div className="value-grid">{values.map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
  <section className="cta"><div className="container"><div className="cta-box"><div><div className="eyebrow">Discover Folus Emporium</div><h2>Explore the products we are building around everyday needs.</h2></div><Link className="btn btn-primary" href="/shop">Visit the Shop</Link></div></div></section>
 </main>
}
