import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Privacy Policy | Folus Emporium',
  description: 'How Folus Emporium collects, uses and protects customer information.'
}

export default function PrivacyPolicyPage(){
 return <main className="support-page"><header className="nav"><div className="container nav-inner"><Link className="brand" href="/"><img src="/folus-emporium-circular-logo.png" alt="Folus Emporium logo"/><span>FOLUS<br/>EMPORIUM<small>Nature’s Goodness, Purely Yours.</small></span></Link><nav className="navlinks"><Link href="/">Home</Link><Link href="/shop">Shop</Link><Link href="/contact">Contact Us</Link></nav></div></header><section className="section"><div className="container" style={{maxWidth:900}}><div className="eyebrow">Legal & privacy</div><h1>Privacy Policy</h1><p>Last updated: 10 September 2026.</p><p>Folus Emporium Ltd respects your privacy. This policy explains the information we collect when you use our website, create an account, place an order or contact us, and how we use that information.</p><h2>Information we collect</h2><p>We may collect your name, email address, phone number, delivery address, account details, order information and communications with us. We may also receive basic technical and usage information when you visit our website.</p><h2>How we use your information</h2><p>We use customer information to create and manage accounts, process and deliver orders, confirm payments, provide customer support, prevent misuse, improve our services and communicate information relating to your purchases.</p><h2>Payments</h2><p>Online payments are processed through our payment service provider. Folus Emporium does not need to store your full payment-card details on this website in order to confirm your transaction.</p><h2>Service providers</h2><p>We may use trusted service providers for website hosting, authentication, database services, payments, analytics, communications and delivery. Information is shared only as reasonably necessary for those services and business operations.</p><h2>Data retention and security</h2><p>We retain information for as long as reasonably necessary for orders, customer service, accounting, legal obligations and legitimate business purposes. We use reasonable technical and organisational safeguards, although no online system can be guaranteed to be completely secure.</p><h2>Your choices</h2><p>You may contact us to ask about the personal information associated with your customer relationship, request corrections where appropriate, or raise a privacy concern.</p><h2>Contact us</h2><p>For privacy questions, contact <a href="mailto:info@folusemporium.com">info@folusemporium.com</a> or use our <Link href="/contact">Contact Us</Link> page.</p><p><Link href="/terms-and-conditions">Read our Terms & Conditions</Link>.</p></div></section></main>
}
