import Link from 'next/link'
import { redirect } from 'next/navigation'
import { revalidatePath } from 'next/cache'
import { createClient } from '@/lib/supabase/server'
import SignOutButton from './sign-out-button'

const stages=['pending','processing','shipped','delivered']
function money(v:number|string|null|undefined){return `₦${Number(v??0).toLocaleString('en-NG')}`}
function label(v:string|undefined){return String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}

async function updateNewsletterPreference(formData:FormData){
 'use server'
 const supabase=await createClient()
 const {data:{user}}=await supabase.auth.getUser()
 if(!user)redirect('/login?next=/account&mode=signin')
 const subscribed=String(formData.get('subscribed')||'')==='true'
 const {error}=await supabase.rpc('set_my_newsletter_subscription',{p_subscribed:subscribed})
 if(error)redirect('/account?newsletter=error')
 revalidatePath('/account')
 redirect(`/account?newsletter=${subscribed?'subscribed':'unsubscribed'}`)
}

export default async function AccountPage({searchParams}:{searchParams?:Promise<Record<string,string|string[]|undefined>>}){
 const params=searchParams?await searchParams:{}
 const supabase=await createClient()
 const {data:authData}=await supabase.auth.getUser()
 const user=authData.user
 if(!user)redirect('/login?next=/account&mode=signin')
 const [{data:profile},{data:orders},{data:newsletterSubscribed}]=await Promise.all([
  supabase.from('profiles').select('full_name,phone,role').eq('id',user.id).maybeSingle(),
  supabase.rpc('get_my_orders'),
  supabase.rpc('get_my_newsletter_preference')
 ])
 const m=user.user_metadata??{},fullName=profile?.full_name||m.full_name||'Customer',phone=profile?.phone||m.phone||'Not provided',address=m.delivery_address||'Not provided',location=[m.delivery_city,m.delivery_state].filter(Boolean).join(', ')||'Not provided',isAdmin=profile?.role==='admin'
 const details=[['Full name',fullName],['Email',user.email||'Not provided'],['Phone',phone],['Delivery address',address],['City / State',location]]
 const newsletterMessage=typeof params.newsletter==='string'?params.newsletter:''
 return <main><header className="nav"><div className="container nav-inner"><Link className="brand" href="/"><img src="/folus-emporium-circular-logo.png" alt="Folus Emporium logo"/><span>FOLUS<br/>EMPORIUM<small>Nature’s Goodness, Purely Yours.</small></span></Link><nav className="navlinks"><Link href="/">Home</Link><Link href="/shop">Shop</Link><Link href="/cart">Cart</Link>{isAdmin?<Link href="/admin/dashboard">Admin</Link>:null}</nav></div></header><section className="section"><div className="container" style={{maxWidth:900}}><div className="eyebrow">{isAdmin?'Administrator account':'Customer account'}</div><h1>My Account</h1><p>Welcome back, {fullName}.</p>
 {isAdmin?<div style={{background:'var(--burgundy)',color:'#fff',borderRadius:20,padding:24,margin:'24px 0'}}><h2 style={{color:'#fff'}}>Folus Emporium Admin Dashboard</h2><p>Manage ecommerce operations from your secure administration dashboard.</p><Link className="btn" style={{background:'#fff',color:'var(--burgundy)'}} href="/admin/dashboard">Open Admin Dashboard</Link></div>:null}
 <div className="cart-summary" style={{position:'static',marginTop:24}}><h2>Your details</h2><div style={{display:'grid',gap:0}}>{details.map(([detailLabel,value],index)=><div key={detailLabel} style={{display:'flex',alignItems:'baseline',gap:8,flexWrap:'wrap',padding:'14px 0',borderBottom:index<details.length-1?'1px solid var(--line)':'none'}}><span style={{fontWeight:600,color:'var(--muted)'}}>{detailLabel}:</span><strong style={{color:'var(--burgundy)',overflowWrap:'anywhere'}}>{value}</strong></div>)}</div><div style={{marginTop:18,paddingTop:18,borderTop:'1px solid var(--line)'}}><div className="eyebrow">Security</div><h3 style={{margin:'5px 0 8px',color:'var(--burgundy)'}}>Password & security</h3><p className="muted" style={{marginTop:0}}>Keep your Folus Emporium account secure by updating your password when needed.</p><Link className="btn btn-outline" href="/account/change-password">Change password</Link></div></div>

 <section style={{marginTop:30,background:'#fff',border:'1px solid var(--line)',borderRadius:18,padding:22}}><div className="eyebrow">Email preferences</div><h2 style={{color:'var(--burgundy)',marginBottom:8}}>Newsletter Preferences</h2><p className="muted" style={{marginTop:0}}>Choose whether you want to receive Folus Emporium offers, new product updates, food tips and newsletters at <strong>{user.email}</strong>.</p>{newsletterMessage==='subscribed'?<div style={{padding:'11px 13px',borderRadius:10,background:'#eef8f0',fontWeight:700,marginBottom:14}}>You are now subscribed to Folus Emporium newsletters.</div>:null}{newsletterMessage==='unsubscribed'?<div style={{padding:'11px 13px',borderRadius:10,background:'#faf2ed',fontWeight:700,marginBottom:14}}>You have unsubscribed from Folus Emporium newsletters.</div>:null}{newsletterMessage==='error'?<div style={{padding:'11px 13px',borderRadius:10,background:'#fff1f1',color:'var(--burgundy)',fontWeight:700,marginBottom:14}}>We could not update your newsletter preference. Please try again.</div>:null}<div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:14,flexWrap:'wrap'}}><div><strong style={{color:newsletterSubscribed?'#176b3a':'var(--burgundy)'}}>{newsletterSubscribed?'Subscribed':'Not subscribed'}</strong><div className="muted" style={{fontSize:13,marginTop:3}}>{newsletterSubscribed?'You can unsubscribe at any time.':'You can subscribe whenever you want.'}</div></div><form action={updateNewsletterPreference}><input type="hidden" name="subscribed" value={newsletterSubscribed?'false':'true'}/><button className={newsletterSubscribed?'btn btn-outline':'btn btn-primary'} type="submit">{newsletterSubscribed?'Unsubscribe':'Subscribe to Newsletter'}</button></form></div></section>

 <section style={{marginTop:38}}><div className="eyebrow">Purchases</div><h2 style={{color:'var(--burgundy)'}}>Order history & tracking</h2><p className="muted">Track each order from confirmation through delivery and review the products, payment and delivery details in one place.</p>{orders?.length? <div style={{display:'grid',gap:16}}>{orders.map((o:any)=>{const current=stages.indexOf(o.status),items=Array.isArray(o.items)?o.items:[];return <article key={o.id} style={{background:'#fff',border:'1px solid var(--line)',borderRadius:18,padding:20}}><div style={{display:'flex',justifyContent:'space-between',gap:16,flexWrap:'wrap'}}><div><strong>Order {o.payment_reference||`#${o.id.slice(0,8).toUpperCase()}`}</strong><p className="muted" style={{margin:'5px 0 0'}}>Placed {new Date(o.created_at).toLocaleString('en-NG')}</p><p className="muted" style={{margin:'3px 0 0'}}>Last updated {new Date(o.updated_at||o.created_at).toLocaleString('en-NG')}</p></div><div style={{textAlign:'right'}}><strong style={{fontSize:18}}>{money(o.total)}</strong><p className="muted" style={{margin:'5px 0 0'}}>Payment: <strong>{label(o.payment_status)}</strong></p></div></div>{o.status==='cancelled'?<div style={{marginTop:16,padding:'11px 13px',borderRadius:10,background:'#fff1f1',color:'var(--burgundy)',fontWeight:700}}>This order has been cancelled.</div>:<div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:6,marginTop:18}}>{stages.map((s,i)=><div key={s} style={{textAlign:'center',padding:'10px 4px',borderRadius:9,background:i<=current?'var(--burgundy)':'#f2ebe5',color:i<=current?'#fff':'var(--muted)',fontSize:11,fontWeight:700,textTransform:'capitalize'}}>{s}</div>)}</div>}
 {items.length?<div style={{marginTop:18,borderTop:'1px solid var(--line)',paddingTop:14}}><strong style={{color:'var(--burgundy)'}}>Items in this order</strong><div style={{display:'grid',gap:0,marginTop:7}}>{items.map((item:any,index:number)=><div key={`${item.product_id||index}-${item.variant_id||index}`} style={{display:'flex',justifyContent:'space-between',gap:14,padding:'10px 0',borderTop:index?'1px solid var(--line)':'none',flexWrap:'wrap'}}><div><strong>{item.product_name||'Product'}</strong><div className="muted" style={{fontSize:13,marginTop:2}}>{item.size_label?`Size: ${item.size_label}`:item.size_grams?`Size: ${item.size_grams}g`:''}{(item.size_label||item.size_grams)?' · ':''}Quantity: {item.quantity}</div></div><strong>{money(item.line_total)}</strong></div>)}</div></div>:null}
 <div style={{display:'grid',gap:5,marginTop:14,paddingTop:14,borderTop:'1px solid var(--line)'}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><span className="muted">Subtotal</span><strong>{money(o.subtotal)}</strong></div>{Number(o.discount_amount||0)>0?<div style={{display:'flex',justifyContent:'space-between',gap:12}}><span className="muted">Discount</span><strong>-{money(o.discount_amount)}</strong></div>:null}<div style={{display:'flex',justifyContent:'space-between',gap:12}}><span className="muted">Delivery fee</span><strong>{money(o.delivery_fee)}</strong></div><div style={{display:'flex',justifyContent:'space-between',gap:12,paddingTop:6,borderTop:'1px solid var(--line)'}}><strong>Total</strong><strong style={{color:'var(--burgundy)'}}>{money(o.total)}</strong></div></div>
 <div style={{display:'grid',gap:4,marginTop:14}}><p className="muted" style={{margin:0}}>Delivery address: {o.delivery_address||'Delivery details on order'}</p><p className="muted" style={{margin:0}}>Delivery zone: {label(o.delivery_zone)||'Not specified'}</p><p className="muted" style={{margin:0}}>Payment method: {o.payment_method==='pay_after_delivery'?'Pay After Delivery':'Paystack'}</p></div><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:16}}><a className="btn btn-outline" href={`/api/orders/${o.id}/document?type=invoice`}>Download Invoice PDF</a>{o.payment_status==='paid'?<a className="btn btn-primary" href={`/api/orders/${o.id}/document?type=receipt`}>Download Payment Receipt PDF</a>:<span className="muted" style={{alignSelf:'center'}}>Payment receipt becomes available after payment is confirmed.</span>}</div></article>})}</div>:<div className="empty"><h3>No orders yet</h3><p>Your purchases and delivery progress will appear here.</p><Link className="btn btn-primary" href="/shop">Start shopping</Link></div>}</section>
 <div style={{display:'flex',gap:12,flexWrap:'wrap',marginTop:28}}><Link className="btn btn-outline" href="/shop">Continue shopping</Link><Link className="btn btn-outline" href="/cart">View cart</Link><SignOutButton/></div></div></section></main>
}
