import Link from 'next/link'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import AdminBreadcrumbs from '@/components/admin-breadcrumbs'
import '../dashboard/dashboard.css'

function money(v:any){return new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(Number(v||0))}
function dateInput(d:Date){return d.toISOString().slice(0,10)}
async function requireAdmin(){const s=await createClient();const {data:a}=await s.auth.getUser();if(!a.user)redirect('/login?next=/admin/reports&mode=signin');const {data:ok}=await s.rpc('get_my_admin_status');if(ok!==true)redirect('/account?admin_error=access');return s}

export default async function ReportsPage({searchParams}:{searchParams:Promise<{from?:string,to?:string}>}){
 const sp=await searchParams; const now=new Date(); const monthStart=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1));
 const from=sp.from||dateInput(monthStart), to=sp.to||dateInput(now); const s=await requireAdmin();
 const fromIso=new Date(`${from}T00:00:00.000Z`).toISOString(); const toIso=new Date(`${to}T23:59:59.999Z`).toISOString();
 const {data,error}=await s.rpc('get_admin_management_reports',{p_from:fromIso,p_to:toIso}); const r:any=data||{}; const x=r.summary||{}, inv=r.inventory||{};
 return <main className="admin-dashboard-shell"><div className="topbar"><div className="container"><span>Folus Emporium Administration</span><span>Management Reports</span></div></div>
 <header className="nav"><div className="container nav-inner"><Link className="brand" href="/admin/dashboard"><img src="/folus-emporium-circular-logo.png" alt="Folus Emporium logo"/><span>FOLUS<br/>EMPORIUM<small>Reports & Analytics</small></span></Link><nav className="navlinks"><Link href="/admin/dashboard">Dashboard</Link><Link href="/admin/products">Products</Link><Link href="/admin/inventory">Inventory</Link><Link href="/admin/orders">Orders</Link><Link href="/admin/customers">Customers</Link><Link href="/account">Account</Link></nav></div></header>
 <section className="section" style={{paddingTop:42}}><div className="container"><AdminBreadcrumbs items={[{label:'Admin',href:'/admin/dashboard'},{label:'Reports & Analytics'}]}/>
 <div className="section-head"><div><div className="eyebrow">Management information</div><h1>Reports & Analytics</h1><p className="muted">Review sales, customers, products, payments and inventory for any reporting period.</p></div></div>
 <form method="get" style={{display:'flex',gap:12,flexWrap:'wrap',alignItems:'end',padding:16,border:'1px solid var(--line)',borderRadius:14,background:'#fff',margin:'18px 0 24px'}}><label>From<br/><input className="input" type="date" name="from" defaultValue={from}/></label><label>To<br/><input className="input" type="date" name="to" defaultValue={to}/></label><button className="btn btn-primary" type="submit">Run report</button><Link className="btn btn-outline" href="/admin/reports">This month</Link></form>
 {error?<div style={{padding:14,background:'#fff1f1',color:'var(--burgundy)',borderRadius:12}}>Unable to load report: {error.message}</div>:null}
 <div className="admin-dashboard-stats"><article className="admin-dashboard-stat"><span>Net revenue</span><strong>{money(x.net_revenue)}</strong><p>Paid, non-cancelled orders</p></article><article className="admin-dashboard-stat"><span>Paid orders</span><strong>{x.paid_orders||0}</strong><p>{x.orders||0} total orders in period</p></article><article className="admin-dashboard-stat"><span>Average order</span><strong>{money(x.average_order_value)}</strong><p>Average paid order value</p></article><article className="admin-dashboard-stat"><span>Customers</span><strong>{x.unique_customers||0}</strong><p>Unique paying customers</p></article><article className="admin-dashboard-stat"><span>Discounts</span><strong>{money(x.discounts)}</strong><p>Discounts granted</p></article><article className="admin-dashboard-stat"><span>Delivery fees</span><strong>{money(x.delivery_fees)}</strong><p>Delivery revenue included</p></article></div>
 <section className="admin-dashboard-panel" style={{marginTop:26}}><div className="section-head"><div><div className="eyebrow">Product performance</div><h2>Sales by product</h2></div></div><div className="admin-dashboard-table-wrap"><table className="admin-dashboard-table"><thead><tr><th>Product</th><th>Units sold</th><th>Sales</th></tr></thead><tbody>{(r.products||[]).length?(r.products||[]).map((p:any)=><tr key={p.product_name}><td><strong>{p.product_name}</strong></td><td>{p.units_sold}</td><td>{money(p.revenue)}</td></tr>):<tr><td colSpan={3}>No paid product sales in this period.</td></tr>}</tbody></table></div></section>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:20,marginTop:22}}><section className="admin-dashboard-panel"><h2>Payment methods</h2>{(r.payment_methods||[]).map((p:any)=><div key={p.method} style={{display:'flex',justifyContent:'space-between',padding:'10px 0',borderBottom:'1px solid var(--line)'}}><span>{String(p.method).replaceAll('_',' ')}</span><strong>{p.orders} · {money(p.revenue)}</strong></div>)}</section><section className="admin-dashboard-panel"><h2>Order statuses</h2>{(r.order_statuses||[]).map((p:any)=><div key={p.status} style={{display:'flex',justifyContent:'space-between',padding:'10px 0',borderBottom:'1px solid var(--line)'}}><span>{p.status}</span><strong>{p.orders}</strong></div>)}</section></div>
 <section className="admin-dashboard-panel" style={{marginTop:22}}><div className="eyebrow">Inventory snapshot</div><h2>Current inventory position</h2><div className="admin-dashboard-stats"><article className="admin-dashboard-stat"><span>Stock units</span><strong>{inv.stock_units||0}</strong></article><article className="admin-dashboard-stat"><span>Retail stock value</span><strong>{money(inv.retail_stock_value)}</strong></article><article className="admin-dashboard-stat"><span>Out of stock</span><strong>{inv.out_of_stock||0}</strong></article><article className="admin-dashboard-stat"><span>Low stock</span><strong>{inv.low_stock||0}</strong></article></div></section>
 <section className="admin-dashboard-panel" style={{marginTop:22}}><div className="eyebrow">Customer value</div><h2>Top customers</h2><div className="admin-dashboard-table-wrap"><table className="admin-dashboard-table"><thead><tr><th>Customer</th><th>Email</th><th>Paid orders</th><th>Spend</th></tr></thead><tbody>{(r.customers||[]).length?(r.customers||[]).map((c:any,i:number)=><tr key={`${c.email}-${i}`}><td>{c.customer_name}</td><td>{c.email||'—'}</td><td>{c.orders}</td><td><strong>{money(c.spend)}</strong></td></tr>):<tr><td colSpan={4}>No paying customers in this period.</td></tr>}</tbody></table></div></section>
 <div style={{marginTop:22,padding:16,borderRadius:14,background:'#fff8e7'}}><strong>Profitability reporting comes next.</strong><p style={{marginBottom:0}}>Cost prices are not yet stored reliably, so this report deliberately does not estimate COGS or gross profit.</p></div>
 </div></section></main>
}